#!/usr/bin/env php
<?php

// Composer
require( __DIR__ . '/vendor/autoload.php' );

// Environment
require( __DIR__ . '/config/env.php' );

// Yii
require( __DIR__ . '/vendor/yiisoft/yii2/Yii.php' );

$config = yii\helpers\ArrayHelper::merge(
    require( __DIR__ . '/config/base.php' ),
    require( __DIR__ . '/config/console.php' )
);

exit(
    ( new yii\console\Application(
        \yii\helpers\ArrayHelper::merge(
            require( __DIR__ . '/config/base.php' ),
            require( __DIR__ . '/config/console.php' )
        )
    ) )->run()
);

